# Generated by Django 4.0.4 on 2022-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_locations_latitude_alter_locations_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
