# Generated by Django 4.0.4 on 2022-07-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_locations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
